create table roles (
  id bigint generated by default as identity primary key,
  role_name varchar(255) not null unique,
  role_is_active boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Insert default roles
INSERT INTO roles (role_name) VALUES 
  ('admin'),
  ('manager'),
  ('user'); 