create table users (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  email varchar(255) not null unique,
  role_id bigint references roles(id),
  user_is_active boolean default true,
  email_verified boolean default false,
  email_verified_at timestamp with time zone,
  activated_at timestamp with time zone default now(),
  inactivated_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Create index on email for faster lookups
CREATE INDEX users_email_idx ON users(email); 