create table leads (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  email varchar(255) unique,
  phone varchar(20) unique,
  lead_product bigint references products(id),
  lead_stage bigint references stages(id),
  assigned_user bigint references users(id),
  lead_source_id bigint references lead_sources(id),
  lead_active_status boolean default true,
  fu_date date,
  fu_hour integer check (fu_hour between 1 and 12),
  fu_minutes integer check (fu_minutes between 0 and 59),
  fu_period varchar(2) check (fu_period in ('AM', 'PM')),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Create composite indexes for faster report generation
CREATE INDEX leads_status_source_idx 
  ON leads(lead_active_status, lead_source_id);

CREATE INDEX leads_source_user_status_idx 
  ON leads(lead_source_id, assigned_user, lead_active_status);

-- Create individual indexes for foreign keys for better join performance
CREATE INDEX leads_product_idx ON leads(lead_product);
CREATE INDEX leads_stage_idx ON leads(lead_stage);
CREATE INDEX leads_assigned_user_idx ON leads(assigned_user);
CREATE INDEX leads_source_idx ON leads(lead_source_id);

-- Create indexes for unique fields
CREATE INDEX leads_email_idx ON leads(email);
CREATE INDEX leads_phone_idx ON leads(phone); 