-- Create lead_notes table
create table lead_notes (
  id bigint generated by default as identity primary key,
  lead_id bigint references leads(id),
  note text not null,
  note_added_by bigint references users(id),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Create lead_documents table
create table lead_documents (
  id bigint generated by default as identity primary key,
  lead_id bigint references leads(id),
  document_path text not null,
  uploaded_by bigint references users(id),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Create indexes for foreign keys to improve join performance
CREATE INDEX lead_notes_lead_id_idx ON lead_notes(lead_id);
CREATE INDEX lead_notes_added_by_idx ON lead_notes(note_added_by);

CREATE INDEX lead_documents_lead_id_idx ON lead_documents(lead_id);
CREATE INDEX lead_documents_uploaded_by_idx ON lead_documents(uploaded_by); 