-- Create custom enum types
CREATE TYPE hotel_star_category AS ENUM ('5', '4', '3', '2', 'Economy', 'Sharing');
CREATE TYPE room_type AS ENUM ('Quint', 'Quad', 'Triple', 'Double', 'Sharing');

-- Create lead_services table
create table lead_services (
  id bigint generated by default as identity primary key,
  lead_id bigint references leads(id),
  service_name varchar(255) not null,
  service_description text,
  service_amount decimal(10,2) not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Create lead_hotels table
create table lead_hotels (
  id bigint generated by default as identity primary key,
  lead_id bigint references leads(id),
  hotel_city varchar(255) not null,
  hotel_name varchar(255) not null,
  hotel_stars hotel_star_category not null,
  hotel_room_type room_type not null,
  number_of_rooms integer not null check (number_of_rooms > 0),
  hotel_total_amount decimal(10,2) not null,
  hotel_checkin_date date not null,
  hotel_checkout_date date not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  -- Add check constraint to ensure checkout date is after checkin date
  constraint valid_date_range 
    check (hotel_checkout_date >= hotel_checkin_date)
);

-- Create indexes for foreign keys to improve join performance
CREATE INDEX lead_services_lead_id_idx ON lead_services(lead_id);
CREATE INDEX lead_hotels_lead_id_idx ON lead_hotels(lead_id);

-- Create indexes for common search fields
CREATE INDEX lead_hotels_city_idx ON lead_hotels(hotel_city);
CREATE INDEX lead_hotels_dates_idx ON lead_hotels(hotel_checkin_date, hotel_checkout_date);
CREATE INDEX lead_hotels_stars_idx ON lead_hotels(hotel_stars);
CREATE INDEX lead_hotels_room_type_idx ON lead_hotels(hotel_room_type); 