-- Custom Umrah Hotels table
CREATE TABLE custom_umrah_hotels (
  id bigint generated by default as identity primary key,
  lead_id bigint references leads(id),
  umrah_city varchar(10) check (umrah_city in ('Makkah', 'Medinah')),
  hotel_name varchar(255),
  checkin_date date,
  checkout_date date,
  hotel_star varchar(10) check (hotel_star in ('5', '4', '3', 'Economy', 'Sharing')),
  room_type varchar(10) check (room_type in ('Quint', 'Quad', 'Triple', 'Double', 'Economy', 'Sharing')),
  number_of_rooms integer ,
  hotel_price decimal(10) ,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Custom Umrah Services table
CREATE TABLE custom_umrah_services (
  id bigint generated by default as identity primary key,
  custom_umrah_hotel_id bigint references custom_umrah_hotels(id) on delete cascade,
  service_name varchar(255) ,
  description text,
  price decimal(10) ,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Custom Umrah Prices table
CREATE TABLE custom_umrah_prices (
  id bigint generated by default as identity primary key,
  custom_umrah_hotel_id bigint references custom_umrah_hotels(id) on delete cascade,
  quotation_amount decimal(10) ,
  buying_amount decimal(10),
  profit decimal(10,2) generated always as (quotation_amount - buying_amount) stored,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Create indexes for better query performance
CREATE INDEX custom_umrah_hotels_lead_id_idx ON custom_umrah_hotels(lead_id);
CREATE INDEX custom_umrah_services_hotel_id_idx ON custom_umrah_services(custom_umrah_hotel_id);
CREATE INDEX custom_umrah_prices_hotel_id_idx ON custom_umrah_prices(custom_umrah_hotel_id); 