-- Invoice table
CREATE TABLE invoices (
  id bigint generated by default as identity primary key,
  invoice_number varchar(20) unique not null,
  created_date date not null,
  due_date date not null,
  bill_to text not null,
  notes text,
  total_amount decimal(10,2) not null,
  amount_received decimal(10,2) default 0,
  remaining_amount decimal(10,2),
  status varchar(20) default 'Pending' check (status in ('Pending', 'Paid', 'Partially Paid')),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Invoice line items table
CREATE TABLE invoice_items (
  id bigint generated by default as identity primary key,
  invoice_id bigint references invoices(id) on delete cascade,
  service_name varchar(255) not null,
  description text,
  amount decimal(10,2) not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Payment history table
CREATE TABLE payment_history (
  id bigint generated by default as identity primary key,
  invoice_id bigint references invoices(id) on delete cascade,
  amount decimal(10,2) not null,
  payment_type varchar(20) not null check (payment_type in ('Cash', 'Online', 'Cheque')),
  payment_date date not null,
  remaining_amount decimal(10,2) not null,
  payment_notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);


-- Create indexes for better query performance
CREATE INDEX invoice_items_invoice_id_idx ON invoice_items(invoice_id);
CREATE INDEX payment_history_invoice_id_idx ON payment_history(invoice_id); 