create table lead_logs (
  id bigint generated by default as identity primary key,
  lead_id bigint references leads(id),
  user_id bigint references users(id),
  action_type varchar(50) not null,
  old_value jsonb,
  new_value jsonb,
  description text,
  created_at timestamp with time zone default now()
);

-- Create indexes for better query performance
CREATE INDEX lead_logs_lead_id_idx ON lead_logs(lead_id);
CREATE INDEX lead_logs_user_id_idx ON lead_logs(user_id);
CREATE INDEX lead_logs_action_type_idx ON lead_logs(action_type); 