create table general_settings (
  id bigint generated by default as identity primary key,
  company_name varchar(255) not null,
  company_phone varchar(50),
  company_email varchar(255),
  company_address text,
  company_logo_url varchar(255),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Insert a default record
INSERT INTO general_settings (
  company_name, 
  company_phone, 
  company_email, 
  company_address
) VALUES (
  'Laibarak CRM', 
  '+923088551111', 
  'info@arazit', 
  'M2 - Main Blouvard Lake City , Lahore'
); 